version: '2'
services:
  nginx:
    image: nginx:1.8.1

    # Redirect Host's 8080 port to Container's 80
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./docker/web_server.conf:/etc/nginx/conf.d/web.conf
      - ./docker/sars_ssl:/etc/ssl/nginx
      - ./docker/proxy_header.conf:/etc/nginx/conf.d/proxy_header.conf
    links:
      - wildfly:web_server
      - db:db

  wildfly:
    build: docker/
    volumes:
      - ./docker/postgresql-9.3-1100.jdbc41.jar:/opt/jboss/wildfly/standalone/deployments/postgresql.jar
      - sarsupload:/var/sars
    volumes_from:
      - filesync
    ports:
      - 8787:8787
      - 9990:9990
    links:
      - smtp:mail_server
      - ec:ec
  db:
    build: ./docker/postgres/
    environment:
      POSTGRES_PASSWORD: x
      POSTGRES_USER: postgres
      POSTGRES_DB: business_traceability
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ~/db_backups:/db_backup
    ports:
      - 5432:5432
  smtp:
    build: ./docker/fakesmtp/
    volumes:
      - ./logs/mail:/var/mail
  filesync:
    build: ./docker/rsync/
    ports:
      - 10873:873
  ec:
    build: docker/elasticsearch
    labels:
      com.ducva.sars: "SARS ElasticSearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
volumes:
  pgdata:
  sarsupload:
