function start(){PF("globalBlockUI_js")&&PF("globalBlockUI_js").block()}function stop(){PF("globalBlockUI_js")&&PF("globalBlockUI_js").unblock()}function checkPCSleep(){return Date.now()-lastTimeCheck>=2*TIME_RATE?($("#hiddenLogout").click(),location.reload(!0),void(lastTimeCheck=Date.now())):(lastTimeCheck=Date.now(),void setTimeout(checkPCSleep,TIME_RATE))}function split(e){return e.split(/\s/g)}function extractLast(e){return split(e).pop()}function changeStatus(){var e=PrimeFaces.widgets.searchButton,t=PrimeFaces.widgets.linkStatus,n=PrimeFaces.widgets.inputIdCompany
1==t.inputs[0].checked?(n.jq[0].value="",n.disable(),e.enable()):(n.enable(),updateSearchButton())}function checkBtnSearch(){var e=PrimeFaces.widgets.customer_code
if(null!=e){var t=PrimeFaces.widgets.searchButtonCustomerCode
e.jq[0].value.length>0&&e.jq[0].value!=customerCodeMask?t.enable():t.disable()}}function disableSelectBtnAfterSearch(){PrimeFaces.widgets.buttonSelect.disable(),PrimeFaces.widgets.accountTable.unselectAllRows(),PrimeFaces.widgets.accountTable.paginator.setPage(0)}function updateFreezeReason(){null!=PrimeFaces.widgets.client_code_status&&("00001"==PrimeFaces.widgets.client_code_status.input[0].value||"09999"==PrimeFaces.widgets.client_code_status.input[0].value?(PrimeFaces.widgets.freezeReason.selectValue(""),document.getElementById("freezeReason").style.visibility="visible",document.getElementById("freezeReasonLabel").style.visibility="visible"):(document.getElementById("freezeReason").style.visibility="hidden",document.getElementById("freezeReasonLabel").style.visibility="hidden"))}function loadFreezeReason(){null!=PrimeFaces.widgets.client_code_status&&("00001"==PrimeFaces.widgets.client_code_status.input[0].value||"09999"==PrimeFaces.widgets.client_code_status.input[0].value?(document.getElementById("freezeReason").style.visibility="visible",document.getElementById("freezeReasonLabel").style.visibility="visible"):(document.getElementById("freezeReason").style.visibility="hidden",document.getElementById("freezeReasonLabel").style.visibility="hidden"))}function enableBtnSelectAfterCancel(){PrimeFaces.widgets.buttonSelect.enable()}function disableSelectBtnAfterSelect(){PrimeFaces.widgets.buttonSelect.disable()}function editSavingPathTable(){document.getElementById("savingPathForm:saveSavingButton").style.display="inline",document.getElementById("savingPathForm:cancelButton").style.display="inline",document.getElementById("savingPathForm:editSavingButton").style.display="none",$(".inputSavingPath")[0].attributes.removeNamedItem("readOnly"),$("#savingPathForm\\:inputSavingPath").removeClass("ui-state-disabled"),currentSavingPath=document.getElementById("savingPathForm:inputSavingPath").value}function saveSavingPathTable(){document.getElementById("savingPathForm:saveSavingButton").style.display="none",document.getElementById("savingPathForm:cancelButton").style.display="none",document.getElementById("savingPathForm:editSavingButton").style.display="inline",$(".inputSavingPath")[0].setAttribute("readOnly","readOnly"),$("#savingPathForm\\:inputSavingPath").addClass("ui-state-disabled")}function cancelSavingPathTable(){document.getElementById("savingPathForm:saveSavingButton").style.display="none",document.getElementById("savingPathForm:cancelButton").style.display="none",document.getElementById("savingPathForm:editSavingButton").style.display="inline",$(".inputSavingPath")[0].setAttribute("readOnly","readOnly"),$("#savingPathForm\\:inputSavingPath").addClass("ui-state-disabled"),document.getElementById("savingPathForm:inputSavingPath").value=currentSavingPath}function addReadOnlyInputText(){$(".inputSavingPath")[0].setAttribute("readOnly","readOnly")}function copyClipboard(e){var t=document.querySelector(e)
t.select(),document.execCommand("copy")}function downloadAllOnlyMe(){var e=$(".param-project-hidden")[0].innerHTML,t=$(".param-project-hidden")[1].innerHTML,n=$(".register-link")
for(i=0;i<n.length;i++){var a=$("<a />").attr("href",location.origin+e+"/rest/bass/download/"+t+"/"+n[i].innerHTML).attr("download",n[i].innerHTML).appendTo("body")
a[0].click(),a.remove()}}function onHover(e){e.classList.add("ui-state-hover")}function normalState(e){e.classList.remove("ui-state-hover")}var isModified=!1,customerCodeMask="____0000",lastTimeCheck=Date.now(),TIME_RATE=1e6
lastTimeCheck=Date.now(),checkPCSleep()
var SetCaretAtEnd=function(e){var t=e.value.length
if(document.selection){var n=document.selection.createRange()
n.moveStart("character",-t),n.moveStart("character",t),n.moveEnd("character",0),n.select()}else(e.selectionStart||"0"==e.selectionStart)&&(e.selectionStart=t,e.selectionEnd=t)},disableMenuFunction=function(e){e.keyCode===$.ui.keyCode.TAB&&$(this).autocomplete("instance").menu.active&&e.preventDefault()},triggerRowEdit=function(){var e=$(".ui-row-editor span.ui-icon-pencil")
e.length>0&&e[0].click()},triggerCancelEditRow=function(){var e=$(".ui-row-editor span.ui-icon-close")
e.length>0&&e[0].click()},setRowDataHandler=function(e){if(this.attributes["data-rk"]){var t=e.data[0],n=e.data[1]
if(sequence>0&&dataRowKey)n&&PrimeFaces.widgets[n].enable(),selectedRowKey=this.attributes["data-rk"].value
else if(sequence>0&&!dataRowKey)n&&PrimeFaces.widgets[n].disable(),selectedRowKey=null
else if(0==sequence){(e.ctrlKey||e.shiftKey)&&(t.unselectAllRows(),t.selectRow($(this)))
var a=$(t.tbody).find("span.ui-icon-check")
if(n&&(a.length>0?PrimeFaces.widgets[n].enable():PrimeFaces.widgets[n].disable()),selectedRowKey=this.attributes["data-rk"].value,"accountTable"==t.widgetVar){var i=$(t.tbody).find("span.ui-icon-check"),s=i.parents("tr").find("input[type=hidden]")
s.length>0&&(idCompany=s[0].value,selectedIdComEntity=s[0].attributes.idComEntity.value)}}sequence=0,null!=PrimeFaces.widgets.sansanCompanyTable&&updateDataCustomerPanel()}},clearAfterChangePage=function(e,t){var n=PrimeFaces.widgets[e]
n&&n.unselectAllRows()
var a=PrimeFaces.widgets[t]
a&&a.disable()},selectedRowKey=null,dataRowKey=null,sequence=0,idCompany=null,selectedIdComEntity=null,initDataTableSelectRow=function(e,t,n,a){$(document).ready(function(){var i=PrimeFaces.widgets[n]
$(document).on("click","#"+e+"\\:"+t+" .ui-chkbox-box",function(){if(sequence++,$(this).find("span")[0].classList.contains("ui-icon-blank"))return void(a&&(PrimeFaces.widgets[a].disable(),dataRowKey=null,idCompany=null,selectedIdComEntity=null))
i.unselectAllRows()
var e=$(this).parents("tr")
if(i.selectRow(e),i.selection.length>1&&(i.selection.splice(0,1),$(i.selectionHolder)[0].value=i.selection[0]),a&&PrimeFaces.widgets[a].enable(),dataRowKey=$(this).parents("tr")[0].attributes["data-rk"].value,"accountTable"==n){var t=$(PrimeFaces.widgets[n].tbody).find("span.ui-icon-check"),s=t.parents("tr").find("input[type=hidden]")
s.length>0&&(idCompany=s[0].value,selectedIdComEntity=s[0].attributes.idComEntity.value)}}),$(document).off("click","#"+e+"\\:"+t+" tr.ui-widget-content",setRowDataHandler)
var s=[i,a]
$(document).on("click","#"+e+"\\:"+t+" tr.ui-widget-content",s,setRowDataHandler)})},selectSansanCompanyTableRow=function(){var e=PrimeFaces.widgets.sansanCompanyTable,t=PrimeFaces.widgets.accountTable.tbody.find("span.ui-icon-check").parents("tr").find("td")[2].innerText
0==t.length&&e.unselectAllRows(),e.selection.length>0&&e.unselectAllRows()
for(var n=$(e.tbody).children(),a=0;a<n.length;a++){var i=n[a].attributes["data-rk"]
if(null!=i)if(i.value==idCompany)e.selectRow(a),selectedRowKey=n[a].attributes["data-rk"].value,updateDataCustomerPanel()
else{var s=$(n[a]).find("input[type=hidden]")[0].attributes.idComEntity
null!=s&&s.value!=selectedIdComEntity&&($(n[a]).find("div.ui-chkbox-box").css("display","none"),$(n[a]).addClass("ui-state-disabled"),$(n[a]).on("click",function(){return!1}))}}},updateDataCustomerPanel=function(){var e=$(PrimeFaces.widgets.sansanCompanyTable.jqId).find("tr[aria-selected=true]")
if(e.length>0){var t=e.find('input[type="hidden"]')[0].value,n=e[0].attributes["data-rk"].value,a=t+"("+n+")"
$("#displaySanCompanyId")[0].innerText=a,$("#displayCompanyName")[0].innerText=e.find("td")[1].innerText,$("#maintenaceCompanyForm\\:hiddenSanCompanyId")[0].value=n}else $("#displaySanCompanyId")[0].innerText="N/A",$("#displayCompanyName")[0].innerText="N/A",$("#maintenaceCompanyForm\\:hiddenSanCompanyId")[0].value="N/A"},updateSearchButton=function(){var e=PrimeFaces.widgets.linkStatus
if(1==e.inputs[1].checked){var t=PrimeFaces.widgets.searchButton,n=PrimeFaces.widgets.inputIdCompany,a=PrimeFaces.widgets.inputCompanyName
n.jq[0].value.length>0||a.jq[0].value.length>0?t.enable():t.disable()}}
