personInChargeSuggestion=function(t,e){$("#psnAutocomplete").on("listviewbeforefilter",function(i,a){console.debug(i)
var n=$(this)
$input=n.prev().find("input")
var o=$input.val()
n.html(""),o.length>0&&(n.listview("refresh"),$.ajax({beforeSend:function(t){t.setRequestHeader("comPointCode",$input.attr("comPointCode")),t.setRequestHeader("companyCode",$input.attr("companyCode"))},url:location.origin+"/business_traceability/rest/dailyreport/suggest/employee/"+o,dataType:"json",crossDomain:!0,success:function(i){i&&i.length>0&&($.each(i,function(i,a){var o=$('<li class="ui-li-static"></li>')
o.data(a)
var s=$("<div></div>"),d=$('<table width="100%"></table>'),r=$("<tr></tr>"),p=$('<td class="arrow-mobile-suggestion-item-title">'+t+":</td>").width(200),l=$('<td class="arrow-mobile-suggestion-item-content">'+a.dai_compemp_name+"</td>")
r.append(p),r.append(l),d.append(r)
var c=$("<tr></tr>"),m=$('<td class="arrow-mobile-suggestion-item-title">'+e+":</td>").width(200),u=$('<td class="arrow-mobile-suggestion-item-content">'+a.dai_employee_post+"</td>")
c.append(m),c.append(u),d.append(c),s.append(d),o.append(s[0].innerHTML),n.append(o)}),console.debug(n.children()),n.children("li").bind("touchstart mousedown",function(t){$input.val($(this).data("dai_compemp_name")),$(this).siblings().addBack().addClass("ui-screen-hidden"),$input.data("item-data",$(this).data()),setDepartmentName([{name:"data",value:JSON.stringify($(this).data())}])}))}}))})},departmentSuggestion=function(t,e){console.debug("init department"),console.debug($("#departmentAutocomplete")),$("#departmentAutocomplete").on("listviewbeforefilter",function(i,a){console.debug("On Change")
var n=$(this)
$input=n.prev().find("input")
var o=$input.val()
n.html(""),n.listview("refresh"),o.length>0&&$.ajax({beforeSend:function(t){t.setRequestHeader("comPointCode",$input.attr("comPointCode")),t.setRequestHeader("companyCode",$input.attr("companyCode"))},url:location.origin+"/business_traceability/rest/dailyreport/suggest/department/"+$input.val(),dataType:"json",crossDomain:!0,success:function(i){console.debug(i),i&&i.length>0&&($.each(i,function(i,a){var o=$('<li class="ui-li-static"></li>')
o.data(a)
var s=$("<div></div>"),d=$('<table width="100%"></table>'),r=$("<tr></tr>"),p=$('<td class="arrow-mobile-suggestion-item-title">'+t+":</td>").width(200),l=$('<td class="arrow-mobile-suggestion-item-content">'+a.dai_employee_post+"</td>")
r.append(p),r.append(l),d.append(r)
var c=$("<tr></tr>"),m=$('<td class="arrow-mobile-suggestion-item-title">'+e+":</td>").width(200),u=$('<td class="arrow-mobile-suggestion-item-content">'+a.dai_compemp_name+"</td>")
c.append(m),c.append(u),d.append(c),s.append(d),o.append(s[0].innerHTML),n.append(o)}),n.children("li").bind("touchstart mousedown",function(t){$input.val($(this).data("dai_employee_post")),$(this).siblings().addBack().addClass("ui-screen-hidden"),$input.data("item-data",$(this).data()),setEmployeeName([{name:"data",value:JSON.stringify($(this).data())}])}))}})})},companySuggestion=function(t,e){$("#companyAutocomplete").on("listviewbeforefilter",function(i,a){var n=$(this)
$input=n.prev().find("input")
var o=$input.val()
n.listview("refresh"),o.length>0&&$.ajax({url:location.origin+"/business_traceability/rest/dailyreport/suggest/company/"+$input.val(),dataType:"json",crossDomain:!0,success:function(i){console.debug(i),i&&i.length>0&&($.each(i,function(i,a){var o=200,s=($(this)[0].offsetWidth-400)/2,d=$('<li  class="ui-li-static"></li>')
d.data(a)
var r=$("<div></div>"),p=$('<table width="100%"></table>'),l=$("<tr></tr>"),c=$('<td class="arrow-mobile-suggestion-item-title">'+t.customerCode+":</td>").width(o),m=$('<td class="arrow-mobile-suggestion-item-content">'+a.com_customer_code+"</td>").width(s),u=$('<td class="arrow-mobile-suggestion-item-title">'+t.companyCode+":</td>").width(o),g=$('<td class="arrow-mobile-suggestion-item-content">'+a.com_company_code+"</td>").width(s)
l.append(c),l.append(m),l.append(u),l.append(g),p.append(l)
var h=$("<tr></tr>"),w=$('<td class="arrow-mobile-suggestion-item-title">'+t.companyName+":</td>").width(o),b=$('<td class="arrow-mobile-suggestion-item-content">'+a.com_company_name+"</td>").width(s),v=$('<td class="arrow-mobile-suggestion-item-title">'+t.companyFurigana+":</td>").width(o),f=$('<td class="arrow-mobile-suggestion-item-content">'+a.com_company_furigana+"</td>").width(s)
h.append(w),h.append(b),h.append(v),h.append(f),p.append(h)
var y=$("<tr></tr>"),_=$('<td class="arrow-mobile-suggestion-item-title">'+t.url+":</td>").width(o),C=$('<td class="arrow-mobile-suggestion-item-content">'+a.com_url+"</td>").width(s),S=$('<td class="arrow-mobile-suggestion-item-title">'+t.typeOfWork+":</td>").width(o),H=$('<td class="arrow-mobile-suggestion-item-content">'+a.worktype+"</td>").width(s)
y.append(_),y.append(C),y.append(S),y.append(H),p.append(y)
var j=$("<tr></tr>"),N=$('<td class="arrow-mobile-suggestion-item-title">'+t.listed+":</td>").width(o),T=$('<td class="arrow-mobile-suggestion-item-content">'+e[a.listed]+"</td>")
j.append(N),j.append(T),p.append(j),r.append(p),d.append(r[0].innerHTML),n.append(d),n.show()}),n.children("li").bind("touchstart mousedown",function(t){$input.val($(this).data("com_company_name")),n.hide(),$(this).siblings().addBack().addClass("ui-screen-hidden"),$input.data("item-data",$(this).data()),setCompany([{name:"data",value:JSON.stringify($(this).data())}])}))}})})}
