(function(){var n,e,t,i,o,f,u,r,c,l,a,d,s
if(!window.Offline)throw new Error("Offline UI brought in without offline.js")
e='<div class="offline-ui"><div class="offline-ui-content"></div></div>',n='<a href class="offline-ui-retry"></a>',o=function(n){var e
return e=document.createElement("div"),e.innerHTML=n,e.children[0]},f=i=null,t=function(n){return l(n),f.className+=" "+n},l=function(n){return f.className=f.className.replace(new RegExp("(^| )"+n.split(" ").join("|")+"( |$)","gi")," ")},r={},u=function(n,e){return t(n),null!=r[n]&&clearTimeout(r[n]),r[n]=setTimeout(function(){return l(n),delete r[n]},1e3*e)},d=function(n){var e,t,i,o
i={day:86400,hour:3600,minute:60,second:1}
for(t in i)if(e=i[t],n>=e)return o=Math.floor(n/e),[o,t]
return["now",""]},a=function(){var u,r
return f=o(e),document.body.appendChild(f),null!=Offline.reconnect&&Offline.getOption("reconnect")&&(f.appendChild(o(n)),u=f.querySelector(".offline-ui-retry"),r=function(n){return n.preventDefault(),Offline.reconnect.tryNow()},null!=u.addEventListener?u.addEventListener("click",r,!1):u.attachEvent("click",r)),t("offline-ui-"+Offline.state),i=f.querySelector(".offline-ui-content")},c=function(){return a(),Offline.on("up",function(){return l("offline-ui-down"),t("offline-ui-up"),u("offline-ui-up-2s",2),u("offline-ui-up-5s",5)}),Offline.on("down",function(){return l("offline-ui-up"),t("offline-ui-down"),u("offline-ui-down-2s",2),u("offline-ui-down-5s",5)}),Offline.on("reconnect:connecting",function(){return t("offline-ui-connecting"),l("offline-ui-waiting")}),Offline.on("reconnect:tick",function(){var n,e,o
return t("offline-ui-waiting"),l("offline-ui-connecting"),o=d(Offline.reconnect.remaining),n=o[0],e=o[1],i.setAttribute("data-retry-in-value",n),i.setAttribute("data-retry-in-unit",e)}),Offline.on("reconnect:stopped",function(){return l("offline-ui-connecting offline-ui-waiting"),i.setAttribute("data-retry-in-value",null),i.setAttribute("data-retry-in-unit",null)}),Offline.on("reconnect:failure",function(){return u("offline-ui-reconnect-failed-2s",2),u("offline-ui-reconnect-failed-5s",5)}),Offline.on("reconnect:success",function(){return u("offline-ui-reconnect-succeeded-2s",2),u("offline-ui-reconnect-succeeded-5s",5)})},"complete"===document.readyState?c():null!=document.addEventListener?document.addEventListener("DOMContentLoaded",c,!1):(s=document.onreadystatechange,document.onreadystatechange=function(){return"complete"===document.readyState&&c(),"function"==typeof s?s.apply(null,arguments):void 0})}).call(this)
